### ISSUE TITLE
Suggestion: Record splitting and merging

### ISSUE THREAD

**Issue by jakehead20** [Pauan/SaltyBetBot#11]
Seeing that not many bots can do this, I'd suggest adding a way to split the records into a JSON file for each month and . This adds the possibility of sharing certain segments of matches in order to improve the data for the algorithm to use.

P.S.: I was planning to write a nodejs program to do it, but I got too lazy. Might just make a simple js file for splitting and one for merging idk

**Comment by Pauan** [comment]
It's undocumented, but there is a [`bin/process-records` program](https://github.com/Pauan/SaltyBetBot/tree/master/bin/process-records) which splits the records into multiple files (1 file for every 100,000 records). It's used because GitHub has file size limits, so I [workaround that](https://github.com/Pauan/SaltyBetBot/tree/master/static/records) by using multiple files.

**Comment by jakehead20** [comment]
Does importing 3 different files merge them into a single record?

**Comment by Pauan** [comment]
Yeah, importing always causes it to merge into existing records.
