### ISSUE TITLE
Only betting 4100

### ISSUE THREAD

**Issue by Tendrefesse** [Pauan/SaltyBetBot#18]
I'm new here so excuse me if this is not a real issue, but since I installed the bot following the readme it as worked fine except it is betting 4100$ every time (I have around 100k and 4100$ isn't my bailout amount in any mode). Have I done something wrong ? 

Thank you !

Edit: It seemed to have bet differently during the tournament and then started betting only 1$ during exhibitions, to finally resume betting 4100$ during matchmaking.

**Comment by Pauan** [comment]
What's the total amount of money that you have?

**Comment by Tendrefesse** [comment]
250 259$

**Comment by Pauan** [comment]
Okay, so until you reach $273,400 it will continue to bet $4,100. After that it will slowly increase until you reach $410,000. After that point it will bet a maximum of 1.5% of your current money ***or*** $32,000 (whichever is lowest).

It does this because the bot tries to win *upsets*, which means that ~87% of the time it will lose. But when it wins, it wins big. This is the optimal way to bet (as proven by years of analysis).

However, since it's losing a lot of the time, if it bet a large amount then it would be very volatile and would quickly run out of money. So it keeps the bets low so that way it will slowly and steadily gain money over time.

**Comment by Pauan** [comment]
I added in [an FAQ](https://github.com/Pauan/SaltyBetBot#faq) which should clarify these questions.
