### ISSUE TITLE
Bot is betting all in every round

### ISSUE THREAD

**Issue by Diamosis** [Pauan/SaltyBetBot#25]
I don't know if this is by design, but the bot is betting all in every time. It can rack up some pretty nice winning streaks but of course it eventually loses. Is there a way I can configure it to bet a different amount?

**Comment by Pauan** [comment]
@Diamosis How much salt do you have?

**Comment by Diamosis** [comment]
My bailout is 375 right now.

**Comment by Pauan** [comment]
Okay, then it *absolutely* should be all-inning. Because your ratio of salt / bailout is so low, you would gain salt *slower* if it was more cautious. It's the same reason why it's better to all-in during tournaments.

Once you reach about $205,000 it will start to be more cautious, just be patient, it will take a couple weeks before you see progress. Keep in mind that even $1,000,000 is a *small* amount of salt (the bot has made me $260,000,000), so you need to be in it for the long haul.
