### ISSUE TITLE
Should the bot vary its bets?

### ISSUE THREAD

**Issue by Lutzy** [Pauan/SaltyBetBot#7]
I've installed via clone and import extension from static, and I have around 150k bucks. The bot always bets exactly 4100 no matter what. Is this expected behavior?

**Comment by Pauan** [comment]
Yup, it sure is! As you gain more money, it will increase the bet amount until it reaches $50,000 per bet, and then it stops there.

I had experimented with a lot of different money strategies, but this ended up being the best. The reason it stops at $50,000 is because if you bet more than that then it starts skewing the odds, so you end up making less money in the long term.

The reason it's betting low for you right now is because you don't have that much money. The bot works by winning huge amounts of money on upsets. But upsets are rare (they only happen ~18% of the time), so you will lose a lot of matches. So if it bets too much money then you'll end up losing everything. So instead it bets a small percentage of your money, so that way you can slowly grow it over time with a low risk of losing money.

You can take a look at the Chart page, which has some settings you can change. You can change the money strategy and the bet strategy. However, the settings only apply to the Chart page, they don't have any effect on the actual betting (because the actual betting always uses the optimal strategy).

**Comment by Lutzy** [comment]
Hmmm, well, it managed to lose all my bucks FeelsBadMan

**Comment by Pauan** [comment]
@Lutzy That's odd, it would have to lose ~36 matches in a row for that to happen (which isn't happening for me).

Could you Export your Match records and send it to me, so I can see what's going on?

**Comment by Lutzy** [comment]
I think I just got exceptionally unlucky. It's made me money over the past week and is now increasing its bets.

**Comment by Pauan** [comment]
@Lutzy I'm glad it's working, though I'd still like to see your data so I can improve the algorithm.

**Comment by Lutzy** [comment]
https://www.dropbox.com/s/fke8u10gqfjpqa2/records.tar.gz?dl=0

**Comment by Pauan** [comment]
@Lutzy Thanks! I took a look, but I don't see any losses. It has steady growth from $150,000 up to $760,000 (it only took a few days to do that). It certainly never lost all your money.

Perhaps you got confused by tournaments? When a tournament starts, your money is reset to $3,700. Then when the tournament ends, your money is restored to how it was before the tournament started (and your tournament winnings are added to that).

Because tournaments reset your money to $3,700, it certainly *looks* like you lost all your money, but rest assured you did not. Because your money is restored at the end of the tournament, that means it's impossible to lose money during a tournament. That's why the bot goes all-in during tournaments, because it has nothing to lose and everything to gain.
